version: "3.9"
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tasker
      POSTGRES_USER: tasker
      POSTGRES_PASSWORD: taskerdb
      # Add these for better stability
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # Add restart policy
    restart: unless-stopped
    # Improved healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskeruser -d taskerdb -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    # Add command to improve connection handling
    command: >
      postgres 
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100

volumes:
  postgres-data: